### PR TITLE
update because of issue #65

### PR DESCRIPTION
**Pull request by wendy2702**
update because of issue #65

### CODE REVIEW

**Comment by Apollon77** [comment]
Thank you ... my idea was to update the whole list somehow, bit dod not had time to look into "how get a full list of regions to  kind of automate that".
Do you have a source? Then we could write a small script that can generate the regions.js file :-)

**Comment by wendy2702** [comment]
Hi Ingo,

full list can be extracted from here:

[DWD JSON](https://www.dwd.de/DWD/warnungen/warnapp/json/warnings.json)

Sorry but i'm not able to extract the regions from the JSON file.

**Comment by Apollon77** [comment]
Aree there really always all regiins present in the warning file?

**Comment by Apollon77** [comment]
Ok, full list is 

https://www.dwd.de/DE/leistungen/opendata/help/warnungen/cap_warncellids_csv.csv?__blob=publicationFile&v=4 ... name is second column

**Comment by Apollon77** [comment]
12.000 Eintries vs 400 that we have ... hmmm .....

**Comment by wendy2702** [comment]
I can modify my list and do some tests if needed

**Comment by Apollon77** [comment]
The question is more if a list of12k entries makes sense as selection :-)

**Comment by wendy2702** [comment]
Maybe it‘s possible to split.

I.e.:

1. Dropdown-Menü with selection of the „Bundesland“
2. Dropdown-Menü with selection of the City/Area
But for this we need a list which contains information which City/Area belongs to which „Bundesland“

**Comment by Apollon77** [comment]
exactly ... and the data are not having this. or we need to check if Materialize has a "filter dropdown" ... so where user can type and entries are filtered

**Comment by wendy2702** [comment]
But this already working.You start typing. a popup with scroll down appears:

image

**Comment by wendy2702** [comment]
Hi just modified the region.js on my system and it's working.

I will do a PR and you can decide if you like to merge or not.

**Comment by wendy2702** [comment]
Hi,

this is not working and i closed the PR.

The List contains more locations as currently used by DWD to announce warnings.

as example:

Stadt Passau has currently 2 warnings active if you check at DWD website but at the JSON you can only find a warning for the whole area around Passau which is called: "Kreis und Stadt Passau"

If i use the regions.js with all entry and select "Stadt Passau" i did not get any warning, to get a warning in need to select "Kreis und Stadt Passau" which is already in the original region.js file.

**Comment by Apollon77** [comment]
grmpf ... I feared that ... thank you for checking!!

**Comment by wendy2702** [comment]
We need to wait until all areas have a warning and then we need to check the JSON which contains the warnings.

**Comment by Apollon77** [comment]
Ok, so we wait for a major weather issue *gg* (but yes this was also my idea)

**Comment by wendy2702** [comment]
Please fins attached a file which contains warnings for all regions.

[DWD_warnings_all_regions.txt](https://github.com/ioBroker/ioBroker.dwd/files/5939707/DWD_warnings_all_regions.txt)

**Comment by wendy2702** [comment]
Please find attached the JSON with warnings for all areas at Germany :-)

[DWD_Warnings_Germany.txt](https://github.com/ioBroker/ioBroker.dwd/files/5950096/DWD_Warnings_Germany.txt)

Maybe you can create a short script to extract the area and city names.

**Comment by Apollon77** [comment]
401 entries ...

```
["Stadt Flensburg","Stadt Kiel","Hansestadt Lübeck","Stadt Neumünster","Kreis Herzogtum Lauenburg","Kreis Segeberg","Kreis Steinburg","Kreis Stormarn","Hansestadt Hamburg","Stadt Braunschweig","Stadt Salzgitter","Stadt Wolfsburg","Kreis Gifhorn","Kreis Göttingen","Kreis Goslar","Kreis Helmstedt","Kreis Northeim","Kreis Peine","Kreis Wolfenbüttel","Region Hannover","Kreis Diepholz","Kreis Hameln-Pyrmont","Kreis Hildesheim","Kreis Holzminden","Kreis Nienburg (Weser)","Kreis Schaumburg","Kreis Celle","Kreis Harburg","Kreis Lüchow-Dannenberg","Kreis Lüneburg","Kreis Osterholz","Kreis Rotenburg (Wümme)","Heidekreis","Kreis Stade","Kreis Uelzen","Kreis Verden","Stadt Delmenhorst","Stadt Emden","Stadt Wilhelmshaven","Kreis Ammerland","Kreis Cloppenburg","Kreis Emsland","Kreis Grafschaft Bentheim","Kreis und Stadt Oldenburg","Kreis und Stadt Osnabrück","Kreis Vechta","Hansestadt Bremen","Stadt Bremerhaven","Stadt Düsseldorf","Stadt Duisburg","Stadt Essen","Stadt Krefeld","Stadt Mönchengladbach","Stadt Mülheim an der Ruhr","Stadt Oberhausen","Stadt Remscheid","Stadt Solingen","Stadt Wuppertal","Kreis Kleve","Kreis Mettmann","Rhein-Kreis Neuss","Kreis Viersen","Kreis Wesel","Bonn","Stadt Köln","Stadt Leverkusen","StädteRegion Aachen","Kreis Düren","Rhein-Erft-Kreis","Kreis Euskirchen","Kreis Heinsberg","Oberbergischer Kreis","Rheinisch-Bergischer Kreis","Rhein-Sieg-Kreis","Stadt Bottrop","Stadt Gelsenkirchen","Stadt Münster","Kreis Borken","Kreis Coesfeld","Kreis Recklinghausen","Kreis Steinfurt","Kreis Warendorf","Stadt Bielefeld","Kreis Gütersloh","Kreis Herford","Kreis Höxter","Kreis Lippe","Kreis Minden-Lübbecke","Kreis Paderborn","Stadt Bochum","Stadt Dortmund","Stadt Hagen","Stadt Hamm","Stadt Herne","Ennepe-Ruhr-Kreis","Hochsauerlandkreis","Märkischer Kreis","Kreis Olpe","Kreis Siegen-Wittgenstein","Kreis Soest","Kreis Unna","Stadt Frankfurt am Main","Stadt Wiesbaden","Kreis Bergstraße","Kreis Darmstadt-Dieburg und Stadt Darmstadt","Kreis Groß-Gerau","Hochtaunuskreis","Main-Kinzig-Kreis","Main-Taunus-Kreis","Odenwaldkreis","Kreis und Stadt Offenbach","Rheingau-Taunus-Kreis","Wetteraukreis","Kreis Gießen","Lahn-Dill-Kreis","Kreis Limburg-Weilburg","Kreis Marburg-Biedenkopf","Vogelsbergkreis","Kreis Fulda","Kreis Hersfeld-Rotenburg","Kreis und Stadt Kassel","Schwalm-Eder-Kreis","Kreis Waldeck-Frankenberg","Werra-Meißner-Kreis","Stadt Koblenz","Kreis Ahrweiler","Kreis Altenkirchen (Westerwald)","Kreis Bad Kreuznach","Kreis Birkenfeld","Kreis Cochem-Zell","Kreis Mayen-Koblenz","Kreis Neuwied","Rhein-Hunsrück-Kreis","Rhein-Lahn-Kreis","Westerwaldkreis","Kreis Bernkastel-Wittlich","Eifelkreis Bitburg-Prüm","Kreis Vulkaneifel","Kreis Trier-Saarburg und Stadt Trier","Stadt Frankenthal (Pfalz)","Stadt Landau in der Pfalz","Stadt Neustadt an der Weinstraße","Stadt Speyer","Stadt Worms","Stadt Zweibrücken","Kreis Alzey-Worms","Kreis Bad Dürkheim","Donnersbergkreis","Kreis Germersheim","Kreis und Stadt Kaiserslautern","Kreis Kusel","Kreis Südliche Weinstraße","Rhein-Pfalz-Kreis und Stadt Ludwigshafen","Kreis Mainz-Bingen und Stadt Mainz","Kreis Südwestpfalz und Stadt Pirmasens","Stadt Stuttgart","Kreis Böblingen","Kreis Esslingen","Kreis Göppingen","Kreis Ludwigsburg","Rems-Murr-Kreis","Kreis und Stadt Heilbronn","Hohenlohekreis","Kreis Schwäbisch Hall","Main-Tauber-Kreis","Kreis Heidenheim","Ostalbkreis","Stadt Baden-Baden","Kreis und Stadt Karlsruhe","Kreis Rastatt","Stadt Mannheim","Neckar-Odenwald-Kreis","Rhein-Neckar-Kreis und Stadt Heidelberg","Kreis Calw","Enzkreis und Stadt Pforzheim","Kreis Freudenstadt","Kreis Breisgau-Hochschwarzwald und Stadt Freiburg","Kreis Emmendingen","Ortenaukreis","Kreis Rottweil","Schwarzwald-Baar-Kreis","Kreis Tuttlingen","Kreis Konstanz","Kreis Lörrach","Kreis Waldshut","Kreis Reutlingen","Kreis Tübingen","Zollernalbkreis","Alb-Donau-Kreis und Stadt Ulm","Kreis Biberach","Bodenseekreis","Kreis Ravensburg","Kreis Sigmaringen","Stadt Ingolstadt","Kreis Altötting","Kreis Berchtesgadener Land","Kreis Bad Tölz-Wolfratshausen","Kreis Dachau","Kreis Ebersberg","Kreis Eichstätt","Kreis Erding","Kreis Freising","Kreis Fürstenfeldbruck","Kreis Garmisch-Partenkirchen","Kreis Landsberg am Lech","Kreis Miesbach","Kreis Mühldorf a. Inn","Kreis und Stadt München","Kreis Neuburg-Schrobenhausen","Kreis Pfaffenhofen a.d. Ilm","Kreis und Stadt Rosenheim","Kreis Starnberg","Kreis Traunstein","Kreis Weilheim-Schongau","Kreis Deggendorf","Kreis Freyung-Grafenau","Kreis Kelheim","Kreis und Stadt Landshut","Kreis und Stadt Passau","Kreis Regen","Kreis Rottal-Inn","Kreis Straubing-Bogen und Stadt Straubing","Kreis Dingolfing-Landau","Stadt Amberg","Stadt Weiden i.d. OPf.","Kreis Amberg-Sulzbach","Kreis Cham","Kreis Neumarkt i.d. OPf.","Kreis Neustadt a.d. Waldnaab","Kreis und Stadt Regensburg","Kreis Schwandorf","Kreis Tirschenreuth","Kreis und Stadt Bamberg","Kreis und Stadt Bayreuth","Kreis und Stadt Coburg","Kreis Forchheim","Kreis und Stadt Hof","Kreis Kronach","Kreis Kulmbach","Kreis Lichtenfels","Kreis Wunsiedel i. Fichtelgebirge","Stadt Erlangen","Stadt Nürnberg","Stadt Schwabach","Kreis und Stadt Ansbach","Kreis Erlangen-Höchstadt","Kreis und Stadt Fürth","Kreis Nürnberger Land","Kreis Neustadt a.d. Aisch-Bad Windsheim","Kreis Roth","Kreis Weißenburg-Gunzenhausen","Kreis und Stadt Aschaffenburg","Kreis Bad Kissingen","Kreis Rhön-Grabfeld","Kreis Haßberge","Kreis Kitzingen","Kreis Miltenberg","Kreis Main-Spessart","Kreis und Stadt Schweinfurt","Kreis und Stadt Würzburg","Stadt Kaufbeuren","Stadt Kempten (Allgäu)","Stadt Memmingen","Kreis Aichach-Friedberg","Kreis und Stadt Augsburg","Kreis Dillingen a.d. Donau","Kreis Günzburg","Kreis Neu-Ulm","Kreis Lindau (Bodensee)","Kreis Ostallgäu","Kreis Unterallgäu","Kreis Donau-Ries","Kreis Oberallgäu","Regionalverband Saarbrücken","Kreis Merzig-Wadern","Kreis Neunkirchen","Kreis Saarlouis","Saarpfalz-Kreis","Kreis St. Wendel","Berlin","Stadt Brandenburg","Stadt Cottbus","Stadt Frankfurt (Oder)","Stadt Potsdam","Kreis Barnim","Kreis Dahme-Spreewald","Kreis Elbe-Elster","Kreis Havelland","Kreis Märkisch-Oderland","Kreis Oberhavel","Kreis Oberspreewald-Lausitz","Kreis Oder-Spree","Kreis Ostprignitz-Ruppin","Kreis Potsdam-Mittelmark","Kreis Prignitz","Kreis Spree-Neiße","Kreis Teltow-Fläming","Kreis Uckermark","Hansestadt Rostock","Stadt Schwerin","Stadt Chemnitz","Erzgebirgskreis","Stadt Dresden","Kreis Meißen","Stadt Leipzig","Kreis Leipzig","Stadt Dessau-Roßlau","Stadt Halle (Saale)","Stadt Magdeburg","Altmarkkreis Salzwedel","Kreis Anhalt-Bitterfeld","Kreis Börde","Burgenlandkreis","Kreis Jerichower Land","Kreis Mansfeld-Südharz","Saalekreis","Salzlandkreis","Kreis Stendal","Kreis Wittenberg","Stadt Erfurt","Stadt Gera","Stadt Jena","Stadt Suhl","Stadt Weimar","Stadt Eisenach","Kreis Eichsfeld","Kreis Nordhausen","Wartburgkreis","Unstrut-Hainich-Kreis","Kyffhäuserkreis","Kreis Schmalkalden-Meiningen","Kreis Gotha","Kreis Sömmerda","Kreis Hildburghausen","Ilm-Kreis","Kreis Weimarer Land","Kreis Sonneberg","Kreis Saalfeld-Rudolstadt","Saale-Holzland-Kreis","Saale-Orla-Kreis","Kreis Greiz","Kreis Altenburger Land","Ostholsteinische Seen","Ostfriesische Küste","Helgoland","Elbe-/Wesermündung","Elbe von Hamburg bis Cuxhaven","Nordfriesische Küste","Flensburg bis Fehmarn","Östlich Fehmarn bis Rügen","Östlich Rügen","Kreis Dithmarschen - Binnenland","Kreis Dithmarschen - Küste","Kreis Nordfriesland - Binnenland","Kreis Nordfriesland - Küste","Kreis Ostholstein - Binnenland","Kreis Ostholstein - Küste","Kreis Pinneberg (ohne Helgoland)","Insel Helgoland","Kreis Plön - Binnenland","Kreis Plön - Küste","Kreis Rendsburg-Eckernförde - Binnenland","Kreis Rendsburg-Eckernförde - Küste","Kreis Schleswig-Flensburg - Binnenland","Kreis Schleswig-Flensburg - Küste","Kreis Cuxhaven - Binnenland","Kreis Cuxhaven - Küste","Kreis Aurich - Binnenland","Kreis Aurich - Küste","Kreis Friesland - Binnenland","Kreis Friesland - Küste","Kreis Leer (ohne Borkum)","Insel Borkum","Kreis Wesermarsch - Binnenland","Kreis Wesermarsch - Küste","Kreis Wittmund - Binnenland","Kreis Wittmund - Küste","Kreis Mecklenburgische Seenplatte - Nord","Kreis Mecklenburgische Seenplatte - West","Kreis Mecklenburgische Seenplatte - Südost","Kreis Rostock - Binnenland Nord","Kreis Rostock - Küste","Kreis Rostock - Binnenland Süd","Kreis Vorpommern-Rügen - Binnenland","Kreis Vorpommern-Rügen - Küste","Kreis Vorpommern-Rügen - Insel Rügen","Kreis Nordwestmecklenburg - Binnenland","Kreis Nordwestmecklenburg - Küste","Kreis Vorpommern-Greifswald - Binnenland Nord","Kreis Vorpommern-Greifswald - Küste Nord","Kreis Vorpommern-Greifswald - Binnenland Süd","Kreis Vorpommern-Greifswald - Küste Süd","Kreis Ludwigslust-Parchim - West","Kreis Ludwigslust-Parchim - Ost","Kreis Mittelsachsen - Tiefland","Kreis Mittelsachsen - Bergland","Vogtlandkreis - Tiefland","Vogtlandkreis - Bergland","Kreis Zwickau - Tiefland","Kreis Zwickau - Bergland","Kreis Bautzen - Tiefland","Kreis Bautzen - Bergland","Kreis Görlitz - Tiefland","Kreis Görlitz - Bergland","Kreis Sächsische Schweiz-Osterzgebirge - Tiefland","Kreis Sächsische Schweiz-Osterzgebirge - westelbisches Bergland","Kreis Sächsische Schweiz-Osterzgebirge - ostelbisches Bergland","Kreis Nordsachsen - Nord","Kreis Nordsachsen - Süd","Kreis Harz - Tiefland","Kreis Harz - Bergland (Oberharz)"]
```

BUT: included here is "Kreis Neustadt a.d. Aisch-Bad Windsheim" ... but we know that it needs to be "Kreis Neustadt a.d. Aisch - Bad Windsheim"

**Comment by wendy2702** [comment]
> BUT: included here is "Kreis Neustadt a.d. Aisch-Bad Windsheim" ... but we know that it needs to be "Kreis Neustadt a.d. Aisch - Bad Windsheim"

Nope.

This is correct: "Kreis Neustadt a.d. Aisch-Bad Windsheim" as this is what we changed last time and it's working.

grafik


This file can be used to build a valid region.js

**Comment by Apollon77** [comment]
aahhh rigth :-)) I misread the other ticket :-))
ok, I do an adapter update

**Comment by wendy2702** [comment]
Perfect!

**Comment by Apollon77** [comment]
2.7.5 on the way, thank you!!

**Pull request merged**
